#!/bin/bash
#
# ufetch-debian - tiny system info for debian
#

## INFO


# probably don't change these
bc="$(tput bold)"		# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"		# reset

# you can change these
lc="${rc}${bc}${c1}"	# labels
nc="${rc}${bc}${c1}"	# user and hostname
ic="${rc}${bc}${c7}"	# info
fc="${rc}${bc}${c1}"	# first color
sc="${rc}${c1}"			# second color

## OUTPUT

cat <<EOF
${fc}
            .__    .___
___  ______ |__| __| _/
\  \/ /  _ \|  |/ __ | 
 \   (  <_> )  / /_/ | 
  \_/ \____/|__\____ | 
                    \/ 
EOF
exit
